name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run static analysis (cppcheck)
      run: pio check -e compile-test --skip-packages -v

    - name: Run Unit Tests
      run: pio test -e compile-test -v

    - name: Build all boards
      run: |
        pio run -e compile-test \
                -e m5stack-core \
                -e m5stack-core2 \
                -e m5stack-atoms3 \
                -e m5stack-dial -v 