name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: List PlatformIO Boards
      run: |
        pio boards m5stack

    - name: Run PlatformIO Check
      run: |
        pio check -e compile-test --skip-packages -v

    - name: Build all target boards
      run: |
        pio run -e m5stack-core -e m5stack-core2 -e m5stack-atoms3 -e m5stack-dial -v

    - name: Run Unit Tests
      run: |
        pio test -e native -v 